### ISSUE TITLE
Block Numbering

### ISSUE THREAD

**Issue by jniegsch** [jniegsch/Group7-PFMAssignment-ElectiveSelection#27]
**Describe the bug**
Check all block calls that numbering is done by ints [3, 4, 5]. Elective and Registration class assume the block is defined this way

**Comment by annejanssens** [comment]
![image](https://user-images.githubusercontent.com/48250419/53986523-b26fb380-411e-11e9-8c11-4efaf0fdd8c5.png)
This is what I see when I want to search for an elective based on block number.
I tried to fix it myself , but it still isn't working

**Comment by annejanssens** [comment]
I have something strange.
There are allready two electives registered, pfm in block 3 and pla in block 4, as can be seen in screenshot below:
![image](https://user-images.githubusercontent.com/48250419/54109998-87b48200-43e0-11e9-8d64-a4436190303d.png)

First I log in as an admin, and press option 7, find an elective.  Then I press 3 to filter on block number.  Then I press 3 to filter on block number 3. I get the message: No matches, as can be seen in screenshot below:
![image](https://user-images.githubusercontent.com/48250419/54110479-d0b90600-43e1-11e9-9e50-a7a2123f1239.png)


What makes it more strange is that after I log in again, and first press option 8. View all electives. The program returns all electives and after I have pressed a key, I return to the admin dashboard. Then I press again option 7. find an elective. I press again 3. To filter on block number. And I press 3 to filter on block number 3. Now the programme does give me the right result?? See screenshots below for these steps:
![image](https://user-images.githubusercontent.com/48250419/54110338-6b651500-43e1-11e9-895b-0759bdd3296b.png)
![image](https://user-images.githubusercontent.com/48250419/54110346-715af600-43e1-11e9-84d4-647a9a4c1978.png)

I have tried all these steps three times in a row and time after time, first the program says there are no matches. And then after I viewed all electives, it is working. In the mean time, I haven't changed any files or anything else. Can you guys check if this happens also to you?

I also tried to find in the code a mistake, but could not find it.
@sandraslotboom @ChristinaHenninger @Tanislas @jniegsch 


I also mentioned that when I try to filter on a wrong block number, for example 1. The programme asks me: Would you like to view the details of one of the electives in the match list? (y/n). I think if a wrong block number is entered, a message should be returned: You entered a wrong block number, please enter 3, 4 or 5. See screenshot below:
![image](https://user-images.githubusercontent.com/48250419/54110691-5c329700-43e2-11e9-806b-efae307efc4d.png)

**Comment by sandraslotboom** [comment]
I have tried the same steps and get the same result. When I make the elective for the first time and search on it (via all filter options, including block) it all works. However, when I log out, log in to another user account and come back to admin, it says that there is no elective in block 3. Then, however, when i print option 8, and then print 7 again on block, it does work again. However, this issue is the same for all filter options (course name, ECTS, block and keywords) 

![Screenshot 2019-03-11 at 14 37 58](https://user-images.githubusercontent.com/48250817/54128135-b3009680-440b-11e9-9325-2df1e1a3155f.png)
![Screenshot 2019-03-11 at 14 40 26](https://user-images.githubusercontent.com/48250817/54128136-b3992d00-440b-11e9-8418-e0b9002f272b.png)
![Screenshot 2019-03-11 at 14 42 33](https://user-images.githubusercontent.com/48250817/54128238-efcc8d80-440b-11e9-8e19-2d222ab2504c.png)

**Comment by ChristinaHenninger** [comment]
I tested it and had the same result as Anne and Sandra.

**Comment by annejanssens** [comment]
@jniegsch See my comment in this issue 9 hours ago for the steps to recreate
